### ISSUE TITLE
image/render.html doesn't work with THUMBNAIL_PRESERVE_FORMAT=True

### ISSUE THREAD

**Issue by gavinwahl** [fusionbox/django-widgy#243]
```
Template error:
In template widgy/contrib/page_builder/templates/widgy/page_builder/image/render.html, error at line 3
   'unicode' object has no attribute 'name'
   1 : {% load thumbnail_libs %}
   2 : 
   3 :  {% sorl_thumbnail self.image.file.name "500x500" upscale=False as im %} 
   4 :   <img src="{{ im.url }}" alt="{{ self.image.label }}">
   5 : {% endthumbnail %}

...

File "sorl/thumbnail/templatetags/thumbnail.py" in render
  58.             return self._render(context)
File "sorl/thumbnail/templatetags/thumbnail.py" in _render
  136.         thumbnail = get_thumbnail(file_, geometry, **options)
File "sorl/thumbnail/shortcuts.py" in get_thumbnail
  8.     return default.backend.get_thumbnail(file_, geometry_string, **options)
File "sorl/thumbnail/base.py" in get_thumbnail
  77.             options.setdefault('format', self._get_format(file_))
File "sorl/thumbnail/base.py" in _get_format
  49.         file_extension = self.file_extension(file_)
File "sorl/thumbnail/base.py" in file_extension
  46.         return os.path.splitext(file_.name)[1].lower()

Exception Type: AttributeError at /widgets/
Exception Value: 'unicode' object has no attribute 'name'
```

I think this was broken by https://github.com/mariocesar/sorl-thumbnail/commit/f4cc08f253b030bd1079b2bc6320c1c5ca3d6505.
